# Generated by Django 3.2.6 on 2021-10-29 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_price', models.FloatField(blank=True, default=None, null=True)),
                ('area', models.FloatField(blank=True, default=None, null=True)),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('resale', models.BooleanField(blank=True, default=None, null=True)),
                ('bhk', models.IntegerField(blank=True, default=None, null=True)),
                ('rera_approved', models.BooleanField(blank=True, default=None, null=True)),
                ('prop_image', models.ImageField(default=None, upload_to='prop_images')),
                ('no_of_shares', models.IntegerField(blank=True, default=None, null=True)),
                ('max_no_of_shares', models.IntegerField(blank=True, default=None, null=True)),
                ('price_per_share', models.FloatField(blank=True, default=None, null=True)),
                ('predicted_price', models.FloatField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('property_date', models.DateField(auto_now_add=True, null=True)),
                ('property_active', models.BooleanField(blank=True, default=True, null=True)),
                ('sold_price', models.FloatField(blank=True, default=None, null=True)),
                ('nearest_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seller_app.city')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_price', models.FloatField(blank=True, default=None, null=True)),
                ('property_details', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='seller_app.property')),
                ('seller_details', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
