# Generated by Django 3.2.5 on 2021-08-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_per_share',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
