# Generated by Django 3.2.5 on 2021-08-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0002_property_price_per_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
