# Generated by Django 3.2.5 on 2021-08-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0003_property_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='max_no_of_shares',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
