# Generated by Django 3.2.6 on 2021-08-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0004_property_max_no_of_shares'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
