# Generated by Django 3.2.6 on 2021-08-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0006_auto_20210804_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
