# Generated by Django 3.2.6 on 2021-08-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0007_auto_20210804_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AddField(
            model_name='property',
            name='predicted_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
