# Generated by Django 3.2.6 on 2021-08-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0008_auto_20210804_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
