# Generated by Django 3.2.6 on 2021-08-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0011_auto_20210826_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='transaction_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
