# Generated by Django 3.2.5 on 2021-08-02 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_shares', models.IntegerField(blank=True, default=None, null=True)),
                ('buyer_details', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('buyer_property', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='seller_app.property')),
            ],
        ),
    ]
