# Generated by Django 3.2.5 on 2021-08-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='buyer_bond',
            field=models.FileField(default=None, upload_to='buyer_bond_file'),
        ),
    ]
