# Generated by Django 3.2.5 on 2021-08-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_app', '0002_buyer_buyer_bond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='buyer_bond',
            field=models.FileField(blank=True, default=None, null=True, upload_to='buyer_bond_file'),
        ),
    ]
