# Generated by Django 3.2.6 on 2021-08-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_app', '0003_alter_buyer_buyer_bond'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='order_id',
            field=models.CharField(default='asd', max_length=30),
            preserve_default=False,
        ),
    ]
