# Generated by Django 3.2.6 on 2021-08-05 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_app', '0004_buyer_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='order_id',
            new_name='buyer_order_id',
        ),
    ]
