# Generated by Django 3.2.6 on 2021-08-26 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buyer_app', '0006_auto_20210826_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='buyer_order_id',
        ),
        migrations.AddField(
            model_name='buyer',
            name='transaction_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('pan', models.CharField(max_length=15)),
                ('account_holder_id', models.TextField(null=True)),
                ('account_id', models.TextField(null=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(max_length=15, null=True)),
                ('mobile_no', models.CharField(max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
