# Generated by Django 3.2.6 on 2021-08-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_app', '0007_auto_20210826_2015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
